# input data
base_dir: /home/mimiliaogo/3DV-2022
data_dir: ${base_dir}/data/chair
dtype: "voxel" # "point" "voxel"
n_points: 2048
# number of voxel grids
n_voxels: 33

# vision model
arch: resnet18

# training
lr: 0.0004
max_iter: 50000

# dataloader
batch_size: 10
num_workers: 2

# logger
log_freq: 1000

# checkpoint
save_freq: 100
load_checkpoint: False

# eval
vis_freq: 100
load_eval_checkpoint: True

