# input data
base_dir: /home/mimiliaogo/3DV-2022
data_dir: ${base_dir}/data/chair
dtype: "mesh" # "point" "voxel" "mesh"
n_points: 1024
# number of voxel grids
n_voxels: 33

# vision model
arch: resnet18

# training
lr: 0.0004
max_iter: 20000

# dataloader
batch_size: 10
num_workers: 2

# logger
log_freq: 1000

# checkpoint
save_freq: 100
load_checkpoint: False

# eval
vis_freq: 20
load_eval_checkpoint: True

# loss weight
# Weight for the chamfer loss
w_chamfer: 1.0 
# Weight for mesh edge loss
w_edge: 1.0 
# Weight for mesh normal consistency
w_normal: 0.01 
# Weight for mesh laplacian smoothing
w_laplacian: 0.1 